http:
  listener:
    host: "localhost"
    port: "9082"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Faheemnayeem1."